[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "cd shared && npm ci && cd ../frontend && npm ci && npm run build"
publish = "frontend/build"

[build.environment]

NPM_VERSION = "7.18"
NODE_VERSION = "16.4"
NODE_ENV = "production"
NODE_OPTIONS = "--max_old_space_size=4096"
