table:
  name: Configuration
  schema: conference
configuration:
  custom_column_names:
    created_at: createdAt
    updated_at: updatedAt
  custom_root_fields: {}
object_relationships:
- name: conference
  using:
    foreign_key_constraint_on: conferenceId
insert_permissions:
- permission:
    backend_only: false
    check:
      _or:
      - _and:
        - conference:
            slug:
              _eq: X-Hasura-Conference-Slug
        - _exists:
            _table:
              name: FlatUserPermission
              schema: public
            _where:
              _and:
              - user_id:
                  _eq: X-Hasura-User-Id
              - slug:
                  _eq: X-Hasura-Conference-Slug
              - permission_name:
                  _eq: CONFERENCE_MANAGE_CONTENT
      - conference:
          createdBy:
            _eq: X-Hasura-User-Id
    columns:
    - conferenceId
    - key
    - value
  role: user
select_permissions:
- permission:
    columns:
    - conferenceId
    - key
    - value
    filter:
      key:
        _in:
        - CLOWDR_APP_VERSION
        - REGISTRATION_URL
        - SUPPORT_ADDRESS
        - SCHEDULE_VIEW_VERSION
        - SPONSORS_LABEL
        - DISABLE_NEARBY_EVENTS
        - THEME_COMPONENT_COLORS
        - DISABLE_ALL_EVENTS_FOR_ITEM
        - VISIBLE_EXHIBITIONS_LABEL
        - HIDDEN_EXHIBITIONS_LABEL
        - FORCE_MENU_SPONSORS_LINK
        - EVENT_BOX_HIDE_EXHIBITION_PEOPLE
  role: unauthenticated
- permission:
    columns:
    - conferenceId
    - created_at
    - key
    - updated_at
    - value
    filter:
      _or:
      - _and:
        - conference:
            slug:
              _eq: X-Hasura-Conference-Slug
        - _exists:
            _table:
              name: FlatUserPermission
              schema: public
            _where:
              _and:
              - user_id:
                  _eq: X-Hasura-User-Id
              - slug:
                  _eq: X-Hasura-Conference-Slug
              - permission_name:
                  _eq: CONFERENCE_MANAGE_CONTENT
      - conference:
          createdBy:
            _eq: X-Hasura-User-Id
      - key:
          _in:
          - CLOWDR_APP_VERSION
          - REGISTRATION_URL
          - SUPPORT_ADDRESS
          - SCHEDULE_VIEW_VERSION
          - ENABLE_BACKSTAGE_STREAM_PREVIEW
          - SPONSORS_LABEL
          - DISABLE_NEARBY_EVENTS
          - VONAGE_MAX_SIMULTANEOUS_SCREEN_SHARES
          - MY_BACKSTAGES_NOTICE
          - THEME_COMPONENT_COLORS
          - DISABLE_ALL_EVENTS_FOR_ITEM
          - VISIBLE_EXHIBITIONS_LABEL
          - HIDDEN_EXHIBITIONS_LABEL
          - FORCE_MENU_SPONSORS_LINK
          - EVENT_BOX_HIDE_EXHIBITION_PEOPLE
  role: user
update_permissions:
- permission:
    check: null
    columns:
    - value
    filter:
      _or:
      - _and:
        - conference:
            slug:
              _eq: X-Hasura-Conference-Slug
        - _exists:
            _table:
              name: FlatUserPermission
              schema: public
            _where:
              _and:
              - user_id:
                  _eq: X-Hasura-User-Id
              - slug:
                  _eq: X-Hasura-Conference-Slug
              - permission_name:
                  _eq: CONFERENCE_MANAGE_CONTENT
      - conference:
          createdBy:
            _eq: X-Hasura-User-Id
  role: user
