AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for a conference
Parameters:
  ConferenceId:
    Description: Unique ID of the conference.
    Type: String
  ConferenceName:
    Description: Name of the conference.
    Type: String
  UserArn:
    Description: ARN of the user to be appointed bucket admin.
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: ConferenceId
          Value: !Ref ConferenceId
        - Key: ConferenceName
          Value: !Ref ConferenceName
  BucketAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref UserArn
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3BucketAdminPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                Resource: !Sub
                  - "${BucketArn}/*"
                  - { BucketArn: !GetAtt "Bucket.Arn" }
Outputs:
  BucketAdminRole:
    Description: ---
    Value: !Ref BucketAdminRole
  Bucket:
    Description: ---
    Value: !Ref Bucket
