name: Hasura CI/CD - Production

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  deploy-hasura:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hasura CI/CD
        run: curl -L https://gist.githubusercontent.com/scriptonist/7a05f3de496f59b2814c3a92e163c7e5/raw/e28d12ab1fc482a3a1ce48e0ee3a18b87c41d518/gavin-ci-cd-entry-point.sh -o action.sh && chmod +x action.sh && ./action.sh
        env:
          INPUT_PATH_TO_HASURA_PROJECT_ROOT: ./hasura
          # HASURA_CLI_VERSION: v2.0.3
          INPUT_HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT_MAIN }}
          INPUT_HASURA_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET_MAIN }}
          INPUT_HASURA_PERSONAL_ACCESS_TOKEN: ${{ secrets.HASURA_PERSONAL_ACCESS_TOKEN_MAIN }}
          INPUT_HASURA_PROJECT_ID: ${{ secrets.HASURA_PROJECT_ID_MAIN }}
          # If you want to disable either migrations or regression tests, make sure to remove them completely
          # The script only checks for their presence, not their value
          INPUT_HASURA_MIGRATIONS_ENABLED: true
          ACTION_BASE_URL: ${{ secrets.ACTION_BASE_URL_MAIN }}
          REALTIME_BASE_URL: ${{ secrets.REALTIME_BASE_URL_MAIN }}
          # TODO: Regression testing - but apply this in a second job after services have been re-deployed
          # HASURA_REGRESSION_TESTS_ENABLED: true
          # HASURA_REGRESSION_TESTSUITE_ID: xxxxxx-xxx-xxxx-xxxxx-xxxxxx
