name: Prettier

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Prettier
        run: npm install prettier
      - name: Run Prettier check
        run: npx prettier --check .
      - name: Run Prettier for failure info
        if: ${{ failure() }}
        run: npx prettier --write .
